# Generated by Django 4.1.2 on 2022-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                ("date", models.CharField(max_length=30)),
                ("value", models.CharField(max_length=30)),
                ("cpf", models.CharField(max_length=30)),
                ("card", models.CharField(max_length=30)),
                ("hour", models.CharField(max_length=30)),
                ("owner_store", models.CharField(max_length=30)),
                ("name_store", models.CharField(max_length=30)),
            ],
        ),
    ]
